<?php

function listOfCountries() {
  echo "
  <option value='Kenyan'>Kenyan</option>
  <option value='Afghanistan'>Afghanistan</option>
  <option value='Albania'>Albania</option>
  <option value='Algeria'>Algeria</option>
  <option value='American Samoa'>American Samoa</option>
  <option value='Andorra'>Andorra</option>
  <option value='Angola'>Angola</option>
  <option value='Anguilla'>Anguilla</option>
  <option value='Antarctica'>Antarctica</option>
  <option value='Antigua'>Antigua</option>
  <option value='Argentina'>Argentina</option>
  <option value='Armenia'>Armenia</option>
  <option value='Aruba'>Aruba</option>
  <option value='Australia'>Australia</option>
  <option value='Austria'>Austria</option>
  <option value='Azerbaijan'>Azerbaijan</option>
  <option value='Bahamas'>Bahamas</option>
  <option value='Bahrain'>Bahrain</option>
  <option value='Bangladesh'>Bangladesh</option>
  <option value='Barbados'>Barbados</option>
  <option value='Belarus'>Belarus</option>
  <option value='Belgium'>Belgium</option>
  <option value='Belize'>Belize</option>
  <option value='Benin'>Benin</option>
  <option value='Bermuda'>Bermuda</option>
  <option value='Bhutan'>Bhutan</option>
  <option value='Bolivia'>Bolivia</option>
  <option value='Bosnia'>Bosnia</option>
  <option value='Botswana'>Botswana</option>
  <option value='Bouvet Island'>Bouvet Island</option>
  <option value='Brazil'>Brazil</option>
  <option value='Britain'>Britain</option>
  <option value='Brunei'>Brunei</option>
  <option value='Bulgaria'>Bulgaria</option>
  <option value='Burkina Faso'>Burkina Faso</option>
  <option value='Burundi'>Burundi</option>
  <option value='CambodiaKH'>Cambodia</option>
  <option value='Cameroon'>Cameroon</option>
  <option value='Canada'>Canada</option>
  <option value='Cape Verde'>Cape Verde</option>
  <option value='Cayman Islands'>Cayman Islands</option>
  <option value='Chad'>Chad</option>
  <option value='Chile'>Chile</option>
  <option value='China'>China</option>
  <option value='Christmas Island'>Christmas Island</option>
  <option value='Cocos'>Cocos</option>
  <option value='Colombia'>Colombia</option>
  <option value='Comoros'>Comoros</option>
  <option value='Congo'>Congo</option>
  <option value='Congo DRC'>Congo DRC</option>
  <option value='Cook Islands'>Cook Islands</option>
  <option value='Costa Rica'>Costa Rica</option>
  <option value='Cote d'Ivoire'>Cote d'Ivoire</option>
  <option value='Croatia'>Croatia</option>
  <option value='Cuba'>Cuba</option>
  <option value='Cyprus'>Cyprus</option>
  <option value='Czech Republic'>Czech Republic</option>
  <option value='Denmark'>Denmark</option>
  <option value='Djibouti'>Djibouti</option>
  <option value='Dominica'>Dominica</option>
  <option value='Dominican Republic'>Dominican Republic</option>
  <option value='East Timor'>East Timor</option>
  <option value='Ecuador'>Ecuador</option>
  <option value='Egypt'>Egypt</option>
  <option value='El Salvador'>El Salvador</option>
  <option value='Equitorial Guinea'>Equitorial Guinea</option>
  <option value='Eritrea'>Eritrea</option>
  <option value='Estonia'>Estonia</option>
  <option value='Ethiopia'>Ethiopia</option>
  <option value='Falkland Islands'>Falkland Islands</option>
  <option value='Faroe Islands'>Faroe Islands</option>
  <option value='Fiji'>Fiji</option>
  <option value='Finland'>Finland</option>
  <option value='France'>France</option>
  <option value='French Guyana'>French Guyana</option>
  <option value='French Polynesia'>French Polynesia</option>
  <option value='French Southern'>French Southern</option>
  <option value='Gabon'>Gabon</option>
  <option value='Gambia'>Gambia</option>
  <option value='Gaza Strip'>Gaza Strip</option>
  <option value='Georgia'>Georgia</option>
  <option value='Germany'>Germany</option>
  <option value='Ghana'>Ghana</option>
  <option value='Gibraltar'>Gibraltar</option>
  <option value='Greece'>Greece</option>
  <option value='Greenland'>Greenland</option>
  <option value='Grenada'>Grenada</option>
  <option value='Guadeloupe'>Guadeloupe</option>
  <option value='Guam'>Guam</option>
  <option value='Guatemala'>Guatemala</option>
  <option value='Guernsey'>Guernsey</option>
  <option value='Guinea'>Guinea</option>
  <option value='Guinea-Bissau'>Guinea-Bissau</option>
  <option value='Guyana'>Guyana</option>
  <option value='Haiti'>Haiti</option>
  <option value='Heard Island'>Heard Island</option>
  <option value='Holy See'>Holy See</option>
  <option value='Honduras'>Honduras</option>
  <option value='Hong Kong'>Hong Kong</option>
  <option value='Hungary'>Hungary</option>
  <option value='Iceland'>Iceland</option>
  <option value='India'>India</option>
  <option value='Indonesia'>Indonesia</option>
  <option value='Iran'>Iran</option>
  <option value='Iraq'>Iraq</option>
  <option value='Ireland'>Ireland</option>
  <option value='Isle of Man'>Isle of Man</option>
  <option value='Israel'>Israel</option>
  <option value='Italy'>Italy</option>
  <option value='Jamaica'>Jamaica</option>
  <option value='Japan'>Japan</option>
  <option value='Jersey'>Jersey</option>
  <option value='Jordan'>Jordan</option>
  <option value='Kazakhstan'>Kazakhstan</option>
  <option value='Kenyan'>Kenyan</option>
  <option value='Kiribati'>Kiribati</option>
  <option value='Kuwait'>Kuwait</option>
  <option value='Kyrgyzstan'>Kyrgyzstan</option>
  <option value='Laos'>Laos</option>
  <option value='Latvia'>Latvia</option>
  <option value='Lebanon'>Lebanon</option>
  <option value='Lesotho'>Lesotho</option>
  <option value='Liberia'>Liberia</option>
  <option value='Libya'>Libya</option>
  <option value='Liechtenstein'>Liechtenstein</option>
  <option value='Lithuania'>Lithuania</option>
  <option value='Luxembourg'>Luxembourg</option>
  <option value='Macau'>Macau</option>
  <option value='Macedonia'>Macedonia</option>
  <option value='Madagascar'>Madagascar</option>
  <option value='Malawi'>Malawi</option>
  <option value='Malaysia'>Malaysia</option>
  <option value='Maldives'>Maldives</option>
  <option value='Mali'>Mali</option>
  <option value='Malta'>Malta</option>
  <option value='Marshall Islands'>Marshall Islands</option>
  <option value='Martinique'>Martinique</option>
  <option value='Mauritania'>Mauritania</option>
  <option value='Mauritius'>Mauritius</option>
  <option value='Mayotte'>Mayotte</option>
  <option value='Mexico'>Mexico</option>
  <option value='Micronesia'>Micronesia</option>
  <option value='Moldova'>Moldova</option>
  <option value='Monaco'>Monaco</option>
  <option value='Mongolia'>Mongolia</option>
  <option value='Montserrat'>Montserrat</option>
  <option value='Morocco'>Morocco</option>
  <option value='Mozambique'>Mozambique</option>
  <option value='Myanmar'>Myanmar</option>
  <option value='Namibia'>Namibia</option>
  <option value='Nauru'>Nauru</option>
  <option value='Nepal'>Nepal</option>
  <option value='Netherlands'>Netherlands</option>
  <option value='Netherlands Antilles'>Netherlands Antilles</option>
  <option value='New Caledonia'>New Caledonia</option>
  <option value='New Zealand'>New Zealand</option>
  <option value='Nicaragua'>Nicaragua</option>
  <option value='Niger'>Niger</option>
  <option value='Nigeria'>Nigeria</option>
  <option value='Niue'>Niue</option>
  <option value='Norfolk Island'>Norfolk Island</option>
  <option value='Northern Mariana Islands'>Northern Mariana Islands</option>
  <option value='North Korea'>North Korea</option>
  <option value='Norway'>Norway</option>
  <option value='Oman'>Oman</option>
  <option value='Pakistan'>Pakistan</option>
  <option value='Palau'>Palau</option>
  <option value='Panama'>Panama</option>
  <option value='Papua New Guinea'>Papua New Guinea</option>
  <option value='Paraguay'>Paraguay</option>
  <option value='Peru'>Peru</option>
  <option value='Philippines'>Philippines</option>
  <option value='Pitcairn Islands'>Pitcairn Islands</option>
  <option value='Poland'>Poland</option>
  <option value='Portugal'>Portugal</option>
  <option value='Puerto Rico'>Puerto Rico</option>
  <option value='Qatar'>Qatar</option>
  <option value='Reunion'>Reunion</option>
  <option value='Romania'>Romania</option>
  <option value='Russia'>Russia</option>
  <option value='Rwanda'>Rwanda</option>
  <option value='Saint Kitts'>Saint Kitts</option>
  <option value='Saint Lucia'>Saint Lucia</option>
  <option value='Saint Vincent'>Saint Vincent</option>
  <option value='Samoa'>Samoa</option>
  <option value='San Marino'>San Marino</option>
  <option value='Sao Tome'>Sao Tome</option>
  <option value='Saudi Arabia'>Saudi Arabia</option>
  <option value='Senegal'>Senegal</option>
  <option value='Serbia'>Serbia</option>
  <option value='Seychelles'>Seychelles</option>
  <option value='Sierra Leone'>Sierra Leone</option>
  <option value='Singapore'>Singapore</option>
  <option value='Slovakia'>Slovakia</option>
  <option value='Slovenia'>Slovenia</option>
  <option value='Solomon Islands'>Solomon Islands</option>
  <option value='Somalia'>Somalia</option>
  <option value='South Africa'>South Africa</option>
  <option value='South Georgia'>South Georgia</option>
  <option value='South Korea'>South Korea</option>
  <option value='Spain'>Spain</option>
  <option value='Sri Lanka'>Sri Lanka</option>
  <option value='St. Helena'>St. Helena</option>
  <option value='St. Pierre'>St. Pierre</option>
  <option value='Sudan'>Sudan</option>
  <option value='Suriname'>Suriname</option>
  <option value='Svalbard'>Svalbard</option>
  <option value='Swaziland'>Swaziland</option>
  <option value='Sweden'>Sweden</option>
  <option value='Switzerland'>Switzerland</option>
  <option value='Syria'>Syria</option>
  <option value='Taiwan'>Taiwan</option>
  <option value='Tajikistan'>Tajikistan</option>
  <option value='Tanzanian'>Tanzanian</option>
  <option value='Thailand'>Thailand</option>
  <option value='Timor-Leste'>Timor-Leste</option>
  <option value='Togo'>Togo</option>
  <option value='Tokelau'>Tokelau</option>
  <option value='Tonga'>Tonga</option>
  <option value='Trinidad'>Trinidad</option>
  <option value='Tunisia'>Tunisia</option>
  <option value='Turkey'>Turkey</option>
  <option value='Turkmenistan'>Turkmenistan</option>
  <option value='Turks'>Turks</option>
  <option value='Tuvalu'>Tuvalu</option>
  <option value='Ugandan'>Ugandan</option>
  <option value='Ukraine'>Ukraine</option>
  <option value='United Arab Emirates'>United Arab Emirates</option>
  <option value='United Kingdom'>United Kingdom</option>
  <option value='United States'>United States</option>
  <option value='United States'>United States</option>
  <option value='Uruguay'>Uruguay</option>
  <option value='Uzbekistan'>Uzbekistan</option>
  <option value='Vanuatu'>Vanuatu</option>
  <option value='Venezuela'>Venezuela</option>
  <option value='Vietnam'>Vietnam</option>
  <option value='Wallis'>Wallis</option>
  <option value='West Bank'>West Bank</option>
  <option value='Western Sahara'>Western Sahara</option>
  <option value='Yemen'>Yemen</option>
  <option value='Zambia'>Zambia</option>
  <option value='Zimbabwe'>Zimbabwe</option>
";
}

function listOfCounties() {
  echo "
  <option value='Nairobi'>Nairobi</option>
  <option value='Baringo'>Baringo</option>
  <option value='Bomet'>Bomet</option>
  <option value='Bungoma'>Bungoma</option>
  <option value='Busia'>Busia</option>
  <option value='Elgeyo Marakwet'>Elgeyo Marakwet</option>
  <option value='Embu'>Embu</option>
  <option value='Garissa'>Garissa</option>
  <option value='Homa Bay'>Homa Bay</option>
  <option value='Isiolo'>Isiolo</option>
  <option value='Kajiado'>Kajiado</option>
  <option value='Kakamega'>Kakamega</option>
  <option value='Kericho'>Kericho</option>
  <option value='Kiambu'>Kiambu</option>
  <option value='Kilifi'>Kilifi</option>
  <option value='Kirinyaga'>Kirinyaga</option>
  <option value='Kisii'>Kisii</option>
  <option value='Kisumu'>Kisumu</option>
  <option value='Kitui'>Kitui</option>
  <option value='Kwale'>Kwale</option>
  <option value='Laikipia'>Laikipia</option>
  <option value='Lamu'>Lamu</option>
  <option value='Machakos'>Machakos</option>
  <option value='Makueni'>Makueni</option>
  <option value='Mandera'>Mandera</option>
  <option value='Marsabit'>Marsabit</option>
  <option value='Meru'>Meru</option>
  <option value='Migori'>Migori</option>
  <option value='Mombasa'>Mombasa</option>
  <option value='Muranga'>Muranga</option>
  <option value='Nairobi'>Nairobi</option>
  <option value='Nakuru'>Nakuru</option>
  <option value='Nandi'>Nandi</option>
  <option value='Narok'>Narok</option>
  <option value='Nyamira'>Nyamira</option>
  <option value='Nyandarua'>Nyandarua</option>
  <option value='Nyeri'>Nyeri</option>
  <option value='Samburu'>Samburu</option>
  <option value='Siaya'>Siaya</option>
  <option value='Taita Taveta'>Taita Taveta</option>
  <option value='Tana River'>Tana River</option>
  <option value='Tharaka Nithi'>Tharaka Nithi</option>
  <option value='Trans Nzoia'>Trans Nzoia</option>
  <option value='Turkana'>Turkana</option>
  <option value='Uasin Gishu'>Uasin Gishu</option>
  <option value='Vihiga'>Vihiga</option>
  <option value='Wajir'>Wajir</option>
  <option value='West Pokot'>West Pokot</option>
  ";
}

function listOfTimes() {
  echo "
  <option value='6:00am'>6:00am</option>
  <option value='6:30am'>6:30am</option>
  <option value='7:00am'>7:00am</option>
  <option value='7:30am'>7:30am</option>
  <option value='8:00am'>8:00am</option>
  <option value='8:30am'>8:30am</option>
  <option value='9:00am'>9:00am</option>
  <option value='9:30am'>9:30am</option>
  <option value='10:00am'>10:00am</option>
  <option value='10:30am'>10:30am</option>
  <option value='11:00am'>11:00am</option>
  <option value='11:30am'>11:30am</option>
  <option value='12:00noon'>12:00noon</option>
  <option value='12:30pm'>12:30pm</option>
  <option value='1:00pm'>1:00pm</option>
  <option value='1:30pm'>1:30pm</option>
  <option value='2:00pm'>2:00pm</option>
  <option value='2:30pm'>2:30pm</option>
  <option value='3:00pm'>3:00pm</option>
  <option value='3:30pm'>3:30pm</option>
  <option value='4:00pm'>4:00pm</option>
  <option value='4:30pm'>4:30pm</option>
  <option value='5:00pm'>5:00pm</option>
  <option value='5:30pm'>5:30pm</option>
  <option value='6:00pm'>6:00pm</option>
  <option value='6:30pm'>6:30pm</option>
  <option value='7:00pm'>7:00pm</option>
  <option value='7:30pm'>7:30pm</option>
  ";
}
function listOfFloors() {
  echo "
  <option value='N/A'>N/A</option>
  <option value='Ground Floor'>Ground Floor</option>
  <option value='1st Floor'>1st Floor</option>
  <option value='2nd Floor'>2nd Floor</option>
  <option value='3rd Floor'>3rd Floor</option>
  <option value='4th Floor'>4th Floor</option>
  <option value='5th Floor'>5th Floor</option>
  <option value='6th Floor'>6th Floor</option>
  <option value='7th Floor'>7th Floor</option>
  <option value='8th Floor'>8th Floor</option>
  <option value='9th Floor'>9th Floor</option>
  <option value='10th Floor'>10th Floor</option>
  <option value='11th Floor'>11th Floor</option>
  <option value='12th Floor'>12th Floor</option>
  <option value='13th Floor'>13th Floor</option>
  <option value='14th Floor'>14th Floor</option>
  <option value='15th Floor'>15th Floor</option>
  <option value='Beyond 15'>Beyond 15</option>
  ";
}
